config/routes.rb
StressMaps::Application.routes.draw do

  resources :employees

  resources :companies do
    member do
      get :employees
    end
  end

  root :to => 'companies#index'

end

app/models/bio_signal.rb
class BioSignal
  include MongoMapper::Document


  key :stress_level, Float
  key :heart_rate, Float

  key :location, Array
  timestamps!

  belongs_to :employee
  #ensure_index [[:location,'2d']]


end

app/models/company.rb
class Company
  include MongoMapper::Document

  key :name, String
  key :departments, Hash
  key :postions, Array
  key :area, Array
  timestamps!

  many :employees

  #ensure_index [[:area,'2d']]

end

app/models/employee.rb
class Employee
  include MongoMapper::EmbeddedDocument

  key :name, String
  key :age,  Integer
  key :chronic_condidtions, Array

  key :location, Array
  key :department, String
  key :department_room, String
  key :postion, String
  key :working_hours, Array

  timestamps!

  many :bio_signals

  #ensure_index [[:location,'2d']]

  def location_lon
    location[1]
  end

  def location_lat
    location[0]
  end

  def location_lon=(lon)
    location[1] = lon.to_f
  end

  def location_lat=(lat)
    location[0] = lat.to_f
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bio_signals_controller.rb
class BioSignalsController < ApplicationController
  # GET /bio_signals
  # GET /bio_signals.json
  def index
    @bio_signals = BioSignal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bio_signals }
    end
  end

  # GET /bio_signals/1
  # GET /bio_signals/1.json
  def show
    @bio_signal = BioSignal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bio_signal }
    end
  end

  # GET /bio_signals/new
  # GET /bio_signals/new.json
  def new
    @bio_signal = BioSignal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bio_signal }
    end
  end

  # GET /bio_signals/1/edit
  def edit
    @bio_signal = BioSignal.find(params[:id])
  end

  # POST /bio_signals
  # POST /bio_signals.json
  def create
    @bio_signal = BioSignal.new(params[:bio_signal])

    respond_to do |format|
      if @bio_signal.save
        format.html { redirect_to @bio_signal, notice: 'Bio signal was successfully created.' }
        format.json { render json: @bio_signal, status: :created, location: @bio_signal }
      else
        format.html { render action: "new" }
        format.json { render json: @bio_signal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bio_signals/1
  # PUT /bio_signals/1.json
  def update
    @bio_signal = BioSignal.find(params[:id])

    respond_to do |format|
      if @bio_signal.update_attributes(params[:bio_signal])
        format.html { redirect_to @bio_signal, notice: 'Bio signal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bio_signal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bio_signals/1
  # DELETE /bio_signals/1.json
  def destroy
    @bio_signal = BioSignal.find(params[:id])
    @bio_signal.destroy

    respond_to do |format|
      format.html { redirect_to bio_signals_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])
    employees_and_bio_signals
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  def employees
    @company = Company.find(params[:id])
    employees_and_bio_signals(params[:date]||'2012-11-1')
    render json: @employees
  end
  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  def employees_and_bio_signals(date='2012-11-1')
    @employees = @company.employees
    #DateTime.parse('2012-10-18')
    date = DateTime.parse(date)
    @bio_signals = {}
    @start_time = DateTime.now
    @end_time = DateTime.new
    @employees.each do |employee|
      bio_signals = BioSignal.where(:employee_id => employee.id, :created_at => {:$gt => (date + 8.hours).to_time, :$lt => (date + 13.hours + 59.minutes + 59.seconds).to_time})
      if bio_signals.present?
        @bio_signals[employee.id] = bio_signals
        bso = bio_signals.order('created_at ASC')
        @start_time = bso.first.created_at if bso.first && @start_time > bso.first.created_at
        @end_time = bso.last.created_at  if bso.last && @end_time < bso.last.created_at
      end
    end
    @employees.select! {|e| @bio_signals.keys.include?(e.id)}
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bio_signals_helper.rb
module BioSignalsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/bio_signals/_form.html.erb
<%= form_for(@bio_signal) do |f| %>
  <% if @bio_signal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bio_signal.errors.count, "error") %> prohibited this bio_signal from being saved:</h2>

      <ul>
      <% @bio_signal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bio_signals/edit.html.erb
<h1>Editing bio_signal</h1>

<%= render 'form' %>

<%= link_to 'Show', @bio_signal %> |
<%= link_to 'Back', bio_signals_path %>

app/views/bio_signals/index.html.erb
<h1>Listing bio_signals</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bio_signals.each do |bio_signal| %>
  <tr>
    <td><%= link_to 'Show', bio_signal %></td>
    <td><%= link_to 'Edit', edit_bio_signal_path(bio_signal) %></td>
    <td><%= link_to 'Destroy', bio_signal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bio signal', new_bio_signal_path %>

app/views/bio_signals/new.html.erb
<h1>New bio_signal</h1>

<%= render 'form' %>

<%= link_to 'Back', bio_signals_path %>

app/views/bio_signals/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_bio_signal_path(@bio_signal) %> |
<%= link_to 'Back', bio_signals_path %>

app/views/companies/_employees.html.erb
<div id='employees'>
  <% @employees.each do |employee|%>
    <%= content_tag 'div', {:class => 'employee', :data => employee.attributes.except('updated_at','created_at', 'name', '_id').merge({:id => employee.id})} do %>
      <% @bio_signals[employee.id].each do |bio_signal|%>
        <%= content_tag 'div', '',{:class => 'bio_signal', :data => bio_signal.attributes.except('updated_at','created_at', '_id').merge({:id => bio_signal.id, :created_at => bio_signal.created_at.to_i})} %>
      <% end %>
    <% end %>
  <% end %>
</div>

<%= hidden_field_tag 'start_time', @start_time.to_i%>
<%= hidden_field_tag 'end_time', @end_time.to_i%>
<%= hidden_field_tag 'current_time', @start_time.to_i%>

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>
<div id="mapContainer" style="width:800px; height:600px; float:left"></div>

<div id="sidebar" style="float:right; margin:20px">
  <h1>Stress Buster</h1>
  <h2><%= @company.name%></h2>
  <h3>Stress on Thursday, 1. November 2012</h3>
  <%= link_to 'Back', '#back', :class => 'time_travel', :id => 'back' %> |
  <%= link_to 'Next', '#next', :class => 'time_travel', :id => 'next' %><br>
  Filter by department: <%= select_tag 'filter_department', options_for_select(@company.departments.keys), :include_blank => true %>
</div>

<%= content_tag 'div','', {:id => 'company', :data => {:id => @company.id,:area_0_lat =>@company.area[0][0],:area_0_lon =>@company.area[0][1],:area_1_lat =>@company.area[1][0],:area_1_lon =>@company.area[1][1]}}, true %>

<%= render 'employees'%>


<%#= link_to 'Edit', edit_company_path(@company) %>
<%#= link_to 'Back', companies_path %>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= link_to 'Show', employee %></td>
    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
    <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StressMaps</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <script src="http://api.maps.nokia.com/2.2.3/jsl.js?with=all" type="text/javascript" charset="utf-8"></script>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>